/* Caso regulatório demonstrativo — nenhum dado ou decisão possui validade oficial. */
let REG_CASE,SEAL_PUBLIC_STATE='REGULAR · ATIVO';

function regularizationInitial(){return {
  stage:1,cnpj:'DEMO-PVH-0084',im:'IM-DEMO-4172',sei:'00000.004172/2026-84',
  responsible:'Marina Nogueira · responsável fictícia',volume:820,operator:'Operador demonstrativo',
  contract:false,pgrs:false,sent:false,pending:false,complement:false,approved:false,published:false,
  events:[{title:'Caso incluído na fila técnica',detail:'Origem: cruzamento demonstrativo SEMEC + cadastro SAMAÚMA.',id:'CAD-DEMO-0084'}]
};}

function resetRegularization(){REG_CASE=regularizationInitial();renderRegularization();updateCircularOpportunity();toast('Caso regulatório reiniciado · nenhum registro oficial foi alterado');}
function prepareRegularizationForProfile(profile){
  if(!REG_CASE)REG_CASE=regularizationInitial();
  if(profile==='gestao'&&!REG_CASE.sent){Object.assign(REG_CASE,{contract:true,pgrs:true,sent:true,complement:true});REG_CASE.events.unshift({title:'Complementação recebida',detail:'Grande gerador · licença atualizada pronta para análise.','id':'COMP-DEMO-0084-R1'});}
  if(profile==='cooperativa'&&!REG_CASE.published){Object.assign(REG_CASE,{contract:true,pgrs:true,sent:true,complement:true,approved:true,published:true});}
  renderRegularization();updateCircularOpportunity();
}
function regEvent(title,detail,id){REG_CASE.events.unshift({title,detail,id});}
function regAllowed(...profiles){return profiles.includes(currentSystemProfile)||currentSystemProfile==='banca';}

function renderRegularization(){
  if(!REG_CASE)REG_CASE=regularizationInitial();
  const steps=document.querySelectorAll('#regJourney .reg-step');
  const visualStage=REG_CASE.published?5:REG_CASE.approved?4:REG_CASE.complement?3:REG_CASE.sent?2:1;
  steps.forEach((el,i)=>{const n=i+1;el.classList.toggle('done',n<visualStage||REG_CASE.published&&n===5);el.classList.toggle('active',n===visualStage&&!REG_CASE.published);});
  const w=document.getElementById('regWorkspace');if(!w)return;
  const holder=currentSystemProfile==='gerador';
  const management=currentSystemProfile==='gestao';
  const role=holder?'GRANDE GERADOR':management?'GESTÃO MUNICIPAL':'MODO BANCA · RESPONSABILIDADES VISÍVEIS';
  w.innerHTML=`<div class="reg-layout"><div class="reg-card"><header><div><h3>Área de trabalho · ${role}</h3><p>Mercado Ipê Roxo · caso fictício · processo ${REG_CASE.sei}</p></div><span class="permission">${holder?'DECLARAR E ACOMPANHAR':management?'ANALISAR E DECIDIR':'FLUXO COMPLETO'}</span></header><div class="reg-body">${regularizationMain()}</div></div><aside><div class="reg-card"><header><div><h3>Trilha do processo</h3><p>Eventos incrementais e atribuídos</p></div></header><div class="reg-body">${REG_CASE.events.map(e=>`<div class="reg-event"><b>${e.title}</b><p>${e.detail}</p><code>${e.id}</code></div>`).join('')}</div></div></aside></div>`;
}

function regularizationMain(){
  if(!REG_CASE.sent)return `<div class="reg-status"><span>ETAPA 1 · AUTODECLARAÇÃO</span><h3>Complete o cadastro técnico</h3><p>O estabelecimento confirma seus dados e apresenta a solução de gerenciamento. Esses valores continuam declarados até serem conciliados.</p></div>
    <div class="reg-grid"><div class="reg-field"><label>CNPJ demonstrativo</label><input value="${REG_CASE.cnpj}" readonly></div><div class="reg-field"><label>Inscrição Mobiliária</label><input value="${REG_CASE.im}" readonly></div><div class="reg-field full"><label>Responsável e contato</label><input value="${REG_CASE.responsible}" readonly></div><div class="reg-field"><label>Geração declarada</label><input value="${REG_CASE.volume} kg/mês" readonly></div><div class="reg-field"><label>Operador informado</label><select><option>${REG_CASE.operator}</option></select></div></div>
    <div class="reg-docs"><button class="reg-doc ${REG_CASE.contract?'on':''}" onclick="regToggleDoc('contract')"><i>${REG_CASE.contract?'✓':'+'}</i><span><b>Contrato do operador</b><small>Documento fictício · PDF demonstrativo</small></span><span class="st ${REG_CASE.contract?'s-reg':'s-not'}">${REG_CASE.contract?'ANEXADO':'PENDENTE'}</span></button><button class="reg-doc ${REG_CASE.pgrs?'on':''}" onclick="regToggleDoc('pgrs')"><i>${REG_CASE.pgrs?'✓':'+'}</i><span><b>PGRS demonstrativo</b><small>Plano e responsável técnico fictícios</small></span><span class="st ${REG_CASE.pgrs?'s-reg':'s-not'}">${REG_CASE.pgrs?'ANEXADO':'PENDENTE'}</span></button></div>
    <div class="reg-actions"><button class="btn" onclick="regSubmit()">Protocolar autodeclaração</button><button class="btn sec" onclick="toast('Rascunho salvo somente nesta demonstração')">Salvar rascunho</button></div>`;

  if(REG_CASE.sent&&!REG_CASE.pending&&!REG_CASE.complement&&!REG_CASE.approved)return `<div class="reg-status"><span>ETAPA 2 · ANÁLISE MUNICIPAL</span><h3>Protocolo recebido e preservado</h3><p>Contrato, PGRS e dados declarados foram relacionados ao processo. O sistema aponta requisitos; a decisão continua humana.</p></div>
    <div class="decision-facts"><div><small>CNPJ + IM</small><b>Conciliados</b></div><div><small>CONTRATO</small><b>Recebido</b></div><div><small>PGRS</small><b>Recebido</b></div><div><small>OPERADOR</small><b>A conferir</b></div></div>
    ${regAllowed('gestao')?`<div class="case-alert"><b>Inconsistência documental encontrada</b><p>A validade informada da licença do operador não coincide com o documento anexado. Solicite complemento sem apagar a declaração original.</p></div><div class="reg-actions"><button class="btn" onclick="regRequestComplement()">Solicitar complementação</button><button class="btn sec" onclick="regApprove()">Aprovar sem pendência</button></div>`:`<div class="empty-action"><b>Aguardando análise da SEMA</b><p>O grande gerador acompanha o prazo e receberá aqui qualquer solicitação de complemento.</p></div>`}`;

  if(REG_CASE.pending&&!REG_CASE.complement)return `<div class="reg-status danger"><span>ETAPA 3 · PENDÊNCIA</span><h3>Complementação solicitada</h3><p>A Prefeitura pediu licença atualizada do operador. A declaração original foi preservada e a pendência não suspende automaticamente serviço público.</p></div><div class="reg-docs"><div class="reg-doc"><i>!</i><span><b>Licença do operador</b><small>Atualizar validade e anexar documento correspondente</small></span><span class="st s-irr">PENDENTE</span></div></div>
    ${regAllowed('gerador')?`<div class="reg-actions"><button class="btn" onclick="regSendComplement()">Enviar licença atualizada</button><button class="btn sec" onclick="toast('Canal de contestação demonstrativo aberto')">Contestar solicitação</button></div>`:`<div class="empty-action"><b>Aguardando resposta do interessado</b><p>O servidor acompanha o prazo, mas não pode preencher o documento em nome do gerador.</p></div>`}`;

  if(REG_CASE.complement&&!REG_CASE.approved)return `<div class="reg-status ok"><span>ETAPA 4 · PRONTO PARA DECISÃO</span><h3>Complementação recebida</h3><p>A nova licença entrou como evento separado. Cadastro, PGRS, contrato e operador estão consistentes no cenário demonstrativo.</p></div><div class="seal-checklist"><div><i>✓</i><b>CNPJ e Inscrição Mobiliária conciliados</b><span>SEMEC · cenário</span></div><div><i>✓</i><b>Contrato e PGRS recebidos</b><span>documentos fictícios</span></div><div><i>✓</i><b>Licença atualizada conferida</b><span>complementação</span></div><div><i>✓</i><b>Processo SEI relacionado</b><span>${REG_CASE.sei}</span></div></div>
    ${regAllowed('gestao')?`<div class="reg-actions"><button class="btn" onclick="regApprove()">Aprovar e liberar emissão</button><button class="btn sec" onclick="regRequestComplement()">Nova pendência</button></div>`:`<div class="empty-action"><b>Aguardando decisão da SEMA</b><p>Somente a unidade municipal competente pode reconhecer a regularidade.</p></div>`}`;

  if(REG_CASE.approved&&!REG_CASE.published)return `<div class="reg-status ok"><span>ETAPA 5 · REGULARIDADE RECONHECIDA</span><h3>Selo PVH-DEMO-0084 emitido</h3><p>A decisão foi atribuída à gestão municipal e pode ser consultada publicamente. O gerador não emitiu o próprio selo.</p></div><div class="decision-facts"><div><small>SITUAÇÃO</small><b>Regular · ativo</b></div><div><small>VALIDADE</small><b>12/08/2027</b></div><div><small>RECICLÁVEIS</small><b>820 kg/mês</b></div><div><small>COMPATIBILIDADE</small><b>92% · cooperativa</b></div></div>
    <div class="circular-callout" style="margin-top:12px"><span class="data-origin calculated">RECOMENDAÇÃO EXPLICÁVEL</span><h3>Há uma oportunidade circular possível</h3><p>Papel, papelão e plástico segregados são compatíveis com a capacidade demonstrativa da Coopera Amazônia. A Prefeitura não impõe fornecedor: o gerador decide se deseja publicar a demanda.</p><div class="reg-actions">${currentSystemProfile==='gestao'?`<button class="btn" disabled>Aguardando autorização do gerador</button>`:`<button class="btn" onclick="regPublishOpportunity()">Autorizar publicação da oportunidade</button>`}<button class="btn sec" onclick="openPublicSeal('PVH-DEMO-0084')">Verificar selo publicamente</button></div></div>`;

  return `<div class="reg-status ok"><span>CASO CONCLUÍDO</span><h3>Regularização virou oportunidade qualificada</h3><p>A situação administrativa permanece no núcleo regulatório; somente os dados necessários da fração reciclável foram encaminhados ao núcleo circular.</p></div><div class="circular-callout"><span class="data-origin declared">AUTORIZADO PELO GERADOR</span><h3>Oportunidade OP-REG-0084 publicada</h3><p>820 kg/mês de recicláveis secos · Nova Porto Velho · compatibilidade 92% · escolha e contratação permanecem voluntárias.</p><div class="reg-actions"><button class="btn" onclick="openCircularOpportunity()">Abrir na área da cooperativa</button><button class="btn sec" onclick="openPublicSeal('PVH-DEMO-0084')">Consultar selo</button></div></div>`;
}

function regToggleDoc(key){if(!regAllowed('gerador')){toast('Somente o grande gerador pode anexar seus documentos');return;}REG_CASE[key]=!REG_CASE[key];renderRegularization();}
function regSubmit(){if(!regAllowed('gerador')){toast('Somente o interessado pode protocolar a autodeclaração');return;}if(!REG_CASE.contract||!REG_CASE.pgrs){toast('Anexe contrato e PGRS demonstrativos antes de protocolar');return;}REG_CASE.sent=true;regEvent('Autodeclaração protocolada','Grande gerador · contrato e PGRS demonstrativos recebidos.','PROT-DEMO-0084');renderRegularization();toast('Protocolo recebido · análise municipal aberta');}
function regRequestComplement(){if(!regAllowed('gestao')){toast('Somente a gestão municipal pode registrar pendência');return;}REG_CASE.pending=true;REG_CASE.complement=false;regEvent('Complementação solicitada','SEMA · licença do operador precisa de atualização.','PEND-DEMO-0084');renderRegularization();toast('Pendência enviada ao grande gerador');}
function regSendComplement(){if(!regAllowed('gerador')){toast('Somente o interessado pode responder à pendência');return;}REG_CASE.complement=true;REG_CASE.pending=false;regEvent('Licença atualizada recebida','Grande gerador · complemento preservado como novo evento.','COMP-DEMO-0084-R1');renderRegularization();toast('Complementação protocolada · pronta para decisão');}
function regApprove(){if(!regAllowed('gestao')){toast('Somente a gestão municipal pode reconhecer a regularidade');return;}REG_CASE.sent=true;REG_CASE.complement=true;REG_CASE.pending=false;REG_CASE.approved=true;regEvent('Regularidade reconhecida e selo emitido','SEMA · decisão demonstrativa vinculada ao processo.','SELO-PVH-DEMO-0084');renderRegularization();toast('Selo emitido pela gestão municipal');}
function regPublishOpportunity(){if(!regAllowed('gerador')){toast('A publicação depende de autorização do gerador privado');return;}REG_CASE.published=true;regEvent('Oportunidade circular autorizada','Grande gerador · apenas a fração reciclável compatível foi publicada.','OP-REG-0084');renderRegularization();updateCircularOpportunity();toast('Oportunidade publicada para avaliação da cooperativa');}
function updateCircularOpportunity(){const el=document.getElementById('regOpportunityBanner');if(!el)return;el.style.display=REG_CASE?.published?'block':'none';}
function openCircularOpportunity(){if(currentSystemProfile==='banca'||currentSystemProfile==='cooperativa')irPara('oper');else selectSystemProfile('cooperativa',{route:'oper'});setTimeout(()=>document.getElementById('regOpportunityBanner')?.scrollIntoView({behavior:'smooth',block:'center'}),120);}

function openPublicSeal(code='PVH-DEMO-0084',options={}){document.getElementById('publicSealInput').value=code;searchPublicSeal();document.getElementById('publicSealPortal').classList.add('on');document.body.style.overflow='hidden';if(options.history!==false)saveNavigationState({screen:'public',code,profile:currentSystemProfile||'banca',route:document.querySelector('.view.on')?.id?.replace('v-','')||'selo',returnable:true});}
function closePublicSeal(options={}){document.getElementById('publicSealPortal').classList.remove('on');document.body.style.overflow='';if(options.history!==false&&history.state?.screen==='public'){if(history.state.returnable)history.back();else{selectSystemProfile('banca',{route:'selo',history:false,silent:true});saveNavigationState({screen:'app',profile:'banca',route:'selo'},true);}}}
function searchPublicSeal(){const input=document.getElementById('publicSealInput'),code=input.value.trim().toUpperCase(),valid=code==='PVH-DEMO-0084';const card=document.getElementById('publicSealCard');card.classList.toggle('invalid',!valid);document.getElementById('publicSealName').textContent=valid?'Mercado Ipê Roxo':'Registro não encontrado';document.getElementById('publicSealCode').textContent=valid?'Código PVH-DEMO-0084 · Porto Velho/RO':'Confira o código informado. Nenhum dado oficial foi consultado.';document.getElementById('publicSealState').textContent=valid?SEAL_PUBLIC_STATE:'NÃO LOCALIZADO';document.getElementById('publicSealUpdated').textContent=new Date().toLocaleString('pt-BR');}

window.addEventListener('load',()=>{if(!REG_CASE)REG_CASE=regularizationInitial();renderRegularization();updateCircularOpportunity();});
